# Note: Smaller values result in less lag. Lift speed less than 0.4 may not work well for non spout servers.
# autoPlace will automatically move players to be fully in the elevator
# checkGlass will make sure all floors have glass blocks (at the cost of possible lag when starting a lift)
# preventEntry will prevent players from entering an active elevator (at the cost of possible lag when lifts are running) 
maxLiftArea: 16
maxHeight: 256
debug: false
autoPlace: true
preventEntry: true
preventLeave: true
checkFloor: true
liftMobs: false
floorBlocks:
- GLASS
- BLACK_STAINED_GLASS
- BLUE_STAINED_GLASS
- BROWN_STAINED_GLASS
- CYAN_STAINED_GLASS
- GRAY_STAINED_GLASS
- GREEN_STAINED_GLASS
- LIGHT_BLUE_STAINED_GLASS
- LIGHT_GRAY_STAINED_GLASS
- LIME_STAINED_GLASS
- MAGENTA_STAINED_GLASS
- ORANGE_STAINED_GLASS
- PINK_STAINED_GLASS
- PURPLE_STAINED_GLASS
- RED_STAINED_GLASS
- WHITE_STAINED_GLASS
- YELLOW_STAINED_GLASS
redstone: false
baseBlockSpeeds:
  IRON_BLOCK: 0.5
STRING_oneFloor: "There is only one floor."
STRING_currentFloor: "Current Floor:"
STRING_dest: "Dest:"
STRING_cantEnter: "Can't enter elevator in use"
STRING_cantLeave: "Can't leave elevator in use"